[package]
name = "bpe_tokenizer_ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
tokenizers = "0.21"
polars = { version = "0.46.0", features = ["parquet", "csv", "lazy", "polars-io"] }
glob = "0.3"

[lib]
crate-type = ["cdylib"]

